### ISSUE TITLE
[SOLVED]cannot load plugin under linux/mono

### ISSUE THREAD

**Issue by deathtrip** [drizzt/KeePass-SerpentCipher#1]
the plugin won't compile under linux, the error i get is : "The plugin cannot be loaded", and it also says it's not compatible with the current version of keepass. i use keepass 2.30 with mono 4.0.3.20

**Comment by drizzt** [comment]
It's not a bug of this plugin.
In order to compile any plugin you need to install mono-complete (on Debian/Ubuntu) or similar package on rpm-based distributions

**Comment by deathtrip** [comment]
i can compile other plugins, including the twofish plugin. have you tested this plugin under mono?

**Comment by drizzt** [comment]
I developed it on mono and I mantain Keepass package on ArchLinux and it works correctly:

```
drizzt@liara ~ % mono --version
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Mon Jul 13 18:57:35 UTC 2015)
drizzt@liara Downloads % unzip -d KeePass-2.30 KeePass-2.30.zip
drizzt@liara Downloads % cd KeePass-2.30/
drizzt@liara KeePass-2.30 % wget https://github.com/drizzt/KeePass-SerpentCipher/releases/download/v1.0/SerpentCipher-1.0.zip
drizzt@liara KeePass-2.30 % unzip SerpentCipher-1.0.zip 
drizzt@liara KeePass-2.30 % mono KeePass.exe
drizzt@liara KeePass-2.30 % ls -l ~/.local/share/KeePass/PluginCache/*/                   
total 44
-rwxr-xr-x 1 drizzt drizzt 41984 Sep  3 15:59 SerpentCipher.dll
drizzt@liara KeePass-2.30 % 
```

Which distro are you using?

**Comment by deathtrip** [comment]
ok, i got it working. it was just a file permission problem. the keepass error message threw me off, and i thought it was a problem with the plugin. thanks for the fast reply.
